### PR TITLE
Resources: translations, appstream metainfo, desktop file update

### PR DESCRIPTION
**Pull request by redtide**
- Added LXQt build tools cmake scripts and related bsd3 license; let me know if this is OK or we can use them installed instead bundle and/or move the license together with the scripts
- Added also lxqt-transupdate command, necessary to update translations manually but not installed; it may conflict with the one in lxqt-build-tools if installed
- Added README, CI file and translations in the project for editing
- The icon is copied in the build dir to be used in the main dialog even if not installed
- Added a Config.cmake file with non translatable strings used in the project, mostly used for the new appdata metainfo file (discussed yesterday in IRC); will need some review (do we have an email for the project? Or I'll remove the `update_contact` meta info
- the desktop file is configured and translated; I changed the original name, generic name and comment because I consider wrong the original, so will need a quick discussion, eventually I'll restore the originals
(see `data/translations/labwc_tweaks.desktop.yaml`)
- Added a small configure report

### CODE REVIEW

**Comment by johanmalm** [comment]
> * Added LXQt build tools cmake scripts and related bsd3 license; let me know if this is OK or we can use them installed instead bundle and/or move the license together with the scripts

>     * Added also lxqt-transupdate command, necessary to update translations manually but not installed; it may conflict with the one in lxqt-build-tools if installed



The 3-clause BSD license is compatible with GPL-2.0, so I'm good with it.
https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

The main thing is obviously to include the copyright notice at the top of the files under BSD 3-clause (which you've done).

It think it's also a good idea to put the files under the different license in a dedicated directory if possible with a copy of the license.

Could we put the content of `bin/` and `cmake/` under a `thirdparty/` or `vendor/` directory? If that messes up the scripts or general translate workflow, could we put the `bin/` file in `cmake/`? If we need other cmake modules in future (that we write ourselves) can we put them in a different directory?

If we need to keep the files under the BSD license in multiple directories, I suggest we create `licenses/GPL-2`
and `licenses/BSD-3CLAUSE`, and then symlink to them.

We should also add a note in README.md as follows:

```
This project is licensed under GPL-2.0-only with files contain SPDX license identifiers to reflect this, except for a third party open source software component (in directory cmake/ (or whatever)) under 3-clause BSD. License files can be found in <wherever we decide to put them>.
```

Can we add a link to where the BSD files have come from (the source?).
 
>     * Added README, CI file and translations in the project for editing
> 
>     * The icon is copied in the build dir to be used in the main dialog even if not installed

Fine. Although under Wayland I don't think there is (yet) a way to obtain that icon - unless CSD is used.

>     * Added a Config.cmake file with non translatable strings used in the project, mostly used for the new appdata metainfo file (discussed yesterday in IRC); will need some review (do we have an email for the project? Or I'll remove the `update_contact` meta info

`set(PROJECT_AUTHOR_EMAIL       "") # Used also as organization email`

We don't have an org e-mail. Do we need to specify this?

`set(PROJECT_DESCRIPTION        "Labwc Wayland window compositor settings")`

Suggest remove the word `window`

`set(PROJECT_ORGANIZATION_NAME  "labwc")  # Might be equal to PROJECT_AUTHOR_NAME`

Yes, suggest we set to PROJECT_AUTHOR_NAME

>     * the desktop file is configured and translated; I changed the original name, generic name and comment because I consider wrong the original, so will need a quick discussion, eventually I'll restore the originals
>       (see `data/translations/labwc_tweaks.desktop.yaml`)

Could you just remove the word `window` (so "window compositor settings" becomes just "compositor settings" and the same for the comment). Otherwise I'm fine with it.


General comment: You've used `labwc_tweaks` in few place. Could we use hyphen (`-`) instead of underscore (`_`). If cmake or the translation stack doesn't like it, don't worry.

**Comment by redtide** [comment]
> It think it's also a good idea to put the files under the different license in a dedicated directory if possible with a copy of the license.

sorry, I don't think so, this screw up the source tree. I think that probably the license is not even needed because those files are used only for building and the shell script to update the language files, they are not compiled in any binary, so the 3 clause are already in the files themselves. (Their license don't even report the copyright names, so looking at it on a second thought it looks quite useless)

> Can we add a link to where the BSD files have come from (the source?).

is this necessary to be done in this PR? I had in mind to do that later once with the language translations status, after enabling weblate for tweaks. As said I would even remove the BSD license, the files explicitely report it and where they come from.

> Fine. Although under Wayland I don't think there is (yet) a way to obtain that icon - unless CSD is used.

I don't understand this, the icon is copied in the build dir and linked to it via defines, or in system in the usual hicolor directory.

> We don't have an org e-mail. Do we need to specify this?

No, so I can remove the part where it should be specified, shouldn't be mandatory.

> Suggest remove the word window

OK

> Yes, suggest we set to PROJECT_AUTHOR_NAME

Not necessary, those are arbitral names I choose, so one or the other is enough, that comment was to explain (and also a self reminder) that those 2 variables could match in some cases if needed.

> Could you just remove the word window (so "window compositor settings" becomes just "compositor settings" and the same for the comment). Otherwise I'm fine with it.

Once is removed in the Config.cmake it changes everywhere it's used, it's the PROJECT_DESCRIPTION variable, which is also used by CMake. The reason I configure the files is to reuse the same variables, defined in only one place.

> General comment: You've used labwc_tweaks in few place. Could we use hyphen (-) instead of underscore (_). If cmake or the translation stack doesn't like it, don't worry.

In brief, the hiphen is used for the project name (so the name of the application, hence the executable) and for the translation strings in the app.
The underscore is because [Appstream](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic) and [Freedesktop naming](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html) rules, was discussed in IRC, we can talk there with Consolatis again about this to find a solution that can be good for anyone.

**Comment by johanmalm** [comment]
> > It think it's also a good idea to put the files under the different license in a dedicated directory if possible with a copy of the license.
> 
> sorry, I don't think so, this screw up the source tree. I think that probably the license is not even needed because those files are used only for building and the shell script to update the language files, they are not compiled in any binary, so the 3 clause are already in the files themselves. (Their license don't even report the copyright names, so looking at it on a second thought it looks quite useless)

Fine. Happy to leave as is. The files have the copyright statement in them which is the main thing.

> > Can we add a link to where the BSD files have come from (the source?).
> 
> is this necessary to be done in this PR? I had in mind to do that later once with the language translations status, after enabling weblate for tweaks. As said I would even remove the BSD license, the files explicitely report it and where they come from.

No. Not needed - just a suggestion.

> > Fine. Although under Wayland I don't think there is (yet) a way to obtain that icon - unless CSD is used.
> 
> I don't understand this, the icon is copied in the build dir and linked to it via defines, or in system in the usual hicolor directory.

I misunderstood. Ignore comment :smile:

> In brief, the hiphen is used for the project name (so the name of the application, hence the executable) and for the translation strings in the app. The underscore is because [Appstream](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic) and [Freedesktop naming](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html) rules, was discussed in IRC, we can talk there with Consolatis again about this to find a solution that can be good for anyone.

Okay. Understand. No need to talk to Consolatis about it. Happy as is.

**Comment by redtide** [comment]
>> set(PROJECT_ORGANIZATION_NAME  "labwc")  # Might be equal to PROJECT_AUTHOR_NAME
>
> Yes, suggest we set to PROJECT_AUTHOR_NAME

I think in this case something like "Labwc Team" sounds better as name/label than "labwc", which is exactly the name of the organization/group (as entity, not "people"). I think you can see what I mean by run CMake and see the result in the build dir.

Maybe @stefonarch would like to give a look to the Italian translations?

**Comment by johanmalm** [comment]
Thanks

**Comment by stefonarch** [comment]
Quick question, for translating support in weblate which license for translations should I choose?
https://translate.lxqt-project.org/guide/labwc/labwc-tweaks/

**Comment by redtide** [comment]
uhm, I didn't know there was a license dedicated for translations, or I forgot something...

**Comment by stefonarch** [comment]
It's only for the translations afaik, to set in weblate.

**Pull request merged**
