### PR TITLE
Port to Qt6 and use .ui file

### PR DESCRIPTION
**Pull request by johanmalm**
...but keep the Gtk version around for the time being.

Also remove gsettings get/set calls (e.g. for gtk theme, icon theme and cursor theme) to keep separation boundaries cleaner for people who may want to use labwc-tweaks to configure the compositor alone and use other settings clients for Gtk and Qt related settings.

Remove the optional call to labwc-gtktheme because it is quite hacky and its Gtk theme parsing is far from ideal.

### CODE REVIEW

**Comment by johanmalm** [comment]
tweaks-qt

**Comment by stefonarch** [comment]
Very nice! It has still that parsing issue with local themes listed twice (if I see it right):

screen_area_dom_08:10:00_

**Comment by johanmalm** [comment]
@stefonarch Thanks for testing. The feedback is very helpful.

Both issues fixed (I think).

> It has still that parsing issue with local themes listed twice

The Qt + Gtk version use the same core-code (which is where the duplicate theme bug was).

I wasn't aware (or had forgotten) about that bug. Now fixed.

> Keyboard layout is buggy too atm, it sees `af Dari` (the first) with `XKB_DEFAULT_LAYOUT=it,ch`

Have fixed that too. We now just use the first language (so `it` in your example).

This is not really an adequate solution though, because we don't really support multiple languages.

Bear with me on this one. I think we need to do a list-view or similar with `add` + `remove` buttons so allow multiple languages.

Wanted to just do the 'level-transfer' to Qt first.

**Comment by stefonarch** [comment]
All fixed, but I don't think to have seen this bunch of errors before:

```
[ 50%] Building C object CMakeFiles/labwc-tweaks.dir/environment.c.o
[ 60%] Building C object CMakeFiles/labwc-tweaks.dir/theme.c.o
/tmp/makepkg/labwc-tweaks-git/src/labwc-tweaks/theme.c: In function ‘theme_find’:
/tmp/makepkg/labwc-tweaks-git/src/labwc-tweaks/theme.c:47:40: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size between 0 and 4095 [-Wformat-truncation=]
   47 |         snprintf(buf, sizeof(buf), "%s/%s", path, dirname);
```

**Comment by stefonarch** [comment]
Btw I'd change "Update" to "Apply".

**Pull request merged**
