### PR TITLE
README: remove screenshot and reference to WIP

### PR DESCRIPTION
**Pull request by johanmalm**

### CODE REVIEW

**Comment by stefonarch** [comment]
Change screenshot instead?


immagine

**Comment by johanmalm** [comment]
Feels like it's going through a period of change, so thought we could hang on a bit until it stabilizes

**Comment by redtide** [comment]
There is a link to the screenshot also in [Config.cmake](../blob/master/Config.cmake#L21)

**Comment by johanmalm** [comment]
> There is a link to the screenshot also in [Config.cmake](../blob/master/Config.cmake#L21)

So, what should I do with `Config.cmake` when removing/changing the screenshot.

**Comment by stefonarch** [comment]
It is used in apps like discover and generates  `/usr/share/metainfo/labwc_tweaks.appdata.xml `.

Ideally there should be always a screenshot with the same name.

**Comment by redtide** [comment]
> > There is a link to the screenshot also in [Config.cmake](../blob/master/Config.cmake#L21)
> 
> So, what should I do with `Config.cmake` when removing/changing the screenshot.

an empty string until it will be replaced later some day with the new screenshot

**Comment by johanmalm** [comment]
Okay. Have tweaked `Config.cmake` too.

Suggest we add a screenshot to the repo when the client has matured a little more.

**Pull request merged**
