### PR TITLE
labwc-tweaks.desktop: Italian translation

### PR DESCRIPTION
**Pull request by redtide**

### CODE REVIEW

**Comment by stefonarch** [comment]
There is something I'm not  100% sure about, but the menu usually will show "GenericName" as tooltip, at least under LXQt it's like that and I've no other DE atm to verify.

screen_area_sab_18:17:49_

**Comment by stefonarch** [comment]
Se poi usi https://github.com/stefonarch/lxqt-notificationd/tree/wip_layer_shell_qt le notifiche non rubano il focus e sono configurabile, solo in fondo non vanno bene

**Comment by Consolatis** [comment]
Maybe we should just use the same for `Name` and `GenericName`. It's a rather specialized application unlike a terminal emulator that could have its own name in `Name` and `Terminal` as `GenericName`.

**Comment by redtide** [comment]
IMO obconf-qt (better than the original obconf) looks good:
```desktop
Name=Openbox Settings
GenericName=Window Manager Settings
Comment=Configure the Openbox window manager
Name[it]=Impostazioni Openbox
GenericName[it]=Impostazioni del gestore finestre
Comment[it]=Configura il gestore finestre Openbox
```
so maybe:
```desktop
Name=Labwc Settings
GenericName=Window Manager (or Compositor, though IDK how to translate it in Italian xD ) Settings
Comment=Configure settings for Labwc
Name[it]=Impostazioni Labwc
GenericName[it]=Impostazioni  del gestore finestre
Comment[it]=Configura il gestore finestre Labwc
```
so renaming Openbox to labwc you could also the [other translations] :P
(obconf-qt is gpl2 too)

[other translations]: https://github.com/lxqt/obconf-qt/tree/master/src/translations

**Comment by stefonarch** [comment]
IMO
```
Name=Labwc Tweaks
GenericName=Configuration for the labwc compositor 
```
(or "windowmanager")

**Comment by johanmalm** [comment]
How about: 

```
Name=Labwc Tweaks
GenericName=Settings
Comment=Settings for systems using the labwc compositor
```

I think we should write it in such a way that it does not limit the scope to the compositor. We already set some gsettings variables and it’s possible we’ll extent do some common clients.

From XDG desktop entry spec:

GenericName | Generic name of the application, for example "Web Browser".

Comment | Tooltip for the entry, for example "View sites on the Internet".

**Comment by redtide** [comment]
I agree, except for the GenericName being too... generic? (following your example would be like just Browser... of what?), I would set it to something like "Compositor Settings".
Though if we could give this not too much importance and being quick/practical with the example I did above we could gain a lot of translations in no time, just by replacing the name of the app, isn't it? Just my opinion.

**Comment by johanmalm** [comment]
Looks like not all applications use GenericName, so we could just leave it out.

gnome-control-center just has Name=Settings

…but yes, I guess it’s rather generic

**Comment by redtide** [comment]
To name a random DE, LXQt, uses the generic name for the tooltips.
e.g.
```
Name=FileZilla
GenericName=FTP client
```
tooltip: "FileZilla (FTP client)" which is useful to explain what it does,

**Pull request closed without merging**
